import "./bootstrap";
import.meta.glob( [
    './../images/**',
] );

import { Alpine, Livewire } from "./../../vendor/livewire/livewire/dist/livewire.esm";
import ActionStreamFilters from "./components/ActionStreamFilters";
import ActionStreamItem from "./components/ActionStreamItem";
import Alert from "./components/Alert";
import CreateDiscussionsObject from "./components/CreateDiscussionsObject";
import CreateDiscussionsOwner from "./components/CreateDiscussionsOwner";
import Qet from "./components/Qet";
import QetItem from "./components/QetItem";
import QuarantineInputStartsAt from "./components/QuarantineInputStartsAt";
import QuarantineSelectPrimaryFaultClassification from "./components/QuarantineSelectPrimaryFaultClassification";
import EquipmentImportForm from "./components/EquipmentImportForm";
import QuarantineReportMistakeForm from "./components/QuarantineReportMistakeForm";
import QuarantineSelectDryHireOpportunity from "./components/QuarantineSelectDryHireOpportunity";
import ResetPasswordForm from "./components/ResetPasswordForm";
import SelectFaultRootCause from "./components/SelectFaultRootCause";
import SelectOpportunity from "./components/SelectOpportunity";
import SelectProduct from "./components/SelectProduct";
import SelectTechnicalSupervisor from "./components/SelectTechnicalSupervisor";
import SideMenu from "./components/SideMenu";
import UploadLog from "./components/UploadLog";
import UserDeleteButton from "./components/UserDeleteButton";
import UserForm from "./components/UserForm";
import ProductionAdministratorForm from "./components/ProductionAdministratorForm";
import ProductionAdministratorsIndex from "./components/ProductionAdministratorsIndex";
import ProductionAdministratorEdit from "./components/ProductionAdministratorEdit";
import TechnicalSupervisorsIndex from "./components/TechnicalSupervisorsIndex";
import TechnicalSupervisorForm from "./components/TechnicalSupervisorForm";
import TechnicalSupervisorEdit from "./components/TechnicalSupervisorEdit";
import QuarantineForm from "./components/QuarantineForm";
import DiscussionForm from "./components/DiscussionForm";
import SelectProject from "./components/SelectProject";

Alpine.data( 'ActionStreamFilters', ActionStreamFilters );
Alpine.data( 'ActionStreamItem', ActionStreamItem );
Alpine.data( 'Alert', Alert );
Alpine.data( 'CreateDiscussionsObject', CreateDiscussionsObject );
Alpine.data( 'CreateDiscussionsOwner', CreateDiscussionsOwner );
Alpine.data( 'Qet', Qet );
Alpine.data( 'QetItem', QetItem );
Alpine.data( 'QuarantineInputStartsAt', QuarantineInputStartsAt );
Alpine.data( 'QuarantineSelectPrimaryFaultClassification', QuarantineSelectPrimaryFaultClassification );
Alpine.data( 'EquipmentImportForm', EquipmentImportForm );
Alpine.data( 'QuarantineSelectDryHireOpportunity', QuarantineSelectDryHireOpportunity );
Alpine.data( 'ResetPasswordForm', ResetPasswordForm );
Alpine.data( 'SelectFaultRootCause', SelectFaultRootCause );
Alpine.data( 'SelectOpportunity', SelectOpportunity );
Alpine.data( 'SelectProduct', SelectProduct );
Alpine.data( 'SelectTechnicalSupervisor', SelectTechnicalSupervisor );
Alpine.data( 'SideMenu', SideMenu );
Alpine.data( 'UploadLog', UploadLog );
Alpine.data( 'UserDeleteButton', UserDeleteButton );
Alpine.data( 'UserForm', UserForm );
Alpine.data( 'QuarantineReportMistakeForm', QuarantineReportMistakeForm );
Alpine.data( 'ProductionAdministratorForm', ProductionAdministratorForm );
Alpine.data( 'ProductionAdministratorsIndex', ProductionAdministratorsIndex );
Alpine.data( 'ProductionAdministratorEdit', ProductionAdministratorEdit );
Alpine.data( 'TechnicalSupervisorsIndex', TechnicalSupervisorsIndex );
Alpine.data( 'TechnicalSupervisorForm', TechnicalSupervisorForm );
Alpine.data( 'TechnicalSupervisorEdit', TechnicalSupervisorEdit );
Alpine.data( 'QuarantineForm', QuarantineForm );
Alpine.data( 'DiscussionForm', DiscussionForm );
Alpine.data( 'SelectProject', SelectProject );

Livewire.start();
